web:
    image: 'lamp-c6'
#    restart: always
    command: /run/start.sh
    ports:
        - '80:80'
    volumes:
        - './run:/run'
    volumes_from:
        - db
db:
    image: 'mysql-c6'
    command: echo 'startbbs mysql-vol start' 
    volumes:
        - startbbs_db:/var/lib/mysql
